title: Jasmine Learnings
email: jasmineanica@gmail.com
description: >-
  A well-organized Jekyll site built from Markdown.
baseurl: ""
url: "https://jasmineanica.com"
theme: minima

header_pages:
  - projects.md
  - posts.md

plugins:
  - jekyll-feed

minima:
  date_format: "%b %-d, %Y"
