title: Jasmine Learnings
email: jasmineanica@gmail.com
description: >-
  A well-organized Jekyll site built from Markdown.
baseurl: "/context"
url: "https://jasmineanica.github.io"
theme: minima

header_pages:
  - about.md

plugins:
  - jekyll-feed

minima:
  date_format: "%b %-d, %Y"
